dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - '6.11'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - webdriver-manager update
  - webdriver-manager start &
  - sleep 3

install:
  - npm install

script:
  - echo "============ Running Tests ============="
  - protractor test.js